[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "gunicorn --bind [::]:$PORT --workers 4 --threads 2 --worker-class gevent --timeout 120 --access-logfile - --error-logfile - app:app"
